server:
  port: 8090
spring:
  application:
    name: hazelcast-demo
  datasource:
    driver-class-name: org.h2.Driver
    username: arian
    password: arian
    url: "jdbc:h2:mem:hzdemo;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
app:
  hazelcast:
    cluster-name: "MS_DEMO_CLUSTER"
    instance-name: "HZ-INSTANCE-1"
    members: 127.0.0.1
